stages:
  - rpm-package
  - local-test
  - rpm-stable

rpm-package-rhel7:
  stage: rpm-package
  script:
    - 'rpm-package.sh'
  except:
    - master

rpm-package-rhel8:
  stage: rpm-package
  script:
    - 'rpm-package.sh rhel8'
  except:
    - master

unit-test:
  stage: local-test
  script:
    - 'unit-test.sh'
  except:
    - master

unit-test-python27:
  stage: local-test
  tags:
    - docker
  script:
    - 'unit-test-virtualenv.sh'
  except:
    - master

unit-test-python36:
  stage: local-test
  tags:
    - docker
  script:
    - 'unit-test-virtualenv.sh python36'
  except:
    - master

rpm-stable:
  stage: rpm-stable
  script:
    - 'rpm-stable.sh'
  only:
    - tags
